# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget nrftools::jlinkarm_nrf_worker nrftools::nrfjprogdll nrftools::highlevelnrfjprog nrftools::nrfdfu nrftools::jlinkarm_nrf51_nrfjprogdll nrftools::jlinkarm_nrf52_nrfjprogdll nrftools::jlinkarm_nrf53_nrfjprogdll nrftools::jlinkarm_nrf91_nrfjprogdll nrftools::jlinkarm_unknown_nrfjprogdll nrftools::nrfjprogexe nrftools::mergehex)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target nrftools::jlinkarm_nrf_worker
add_executable(nrftools::jlinkarm_nrf_worker IMPORTED)

# Create imported target nrftools::nrfjprogdll
add_library(nrftools::nrfjprogdll SHARED IMPORTED)

# Create imported target nrftools::highlevelnrfjprog
add_library(nrftools::highlevelnrfjprog SHARED IMPORTED)

set_target_properties(nrftools::highlevelnrfjprog PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target nrftools::nrfdfu
add_library(nrftools::nrfdfu SHARED IMPORTED)

# Create imported target nrftools::jlinkarm_nrf51_nrfjprogdll
add_library(nrftools::jlinkarm_nrf51_nrfjprogdll SHARED IMPORTED)

set_target_properties(nrftools::jlinkarm_nrf51_nrfjprogdll PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "nRF_FAMILY=NRF51_FAMILY"
)

# Create imported target nrftools::jlinkarm_nrf52_nrfjprogdll
add_library(nrftools::jlinkarm_nrf52_nrfjprogdll SHARED IMPORTED)

set_target_properties(nrftools::jlinkarm_nrf52_nrfjprogdll PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "nRF_FAMILY=NRF52_FAMILY"
)

# Create imported target nrftools::jlinkarm_nrf53_nrfjprogdll
add_library(nrftools::jlinkarm_nrf53_nrfjprogdll SHARED IMPORTED)

set_target_properties(nrftools::jlinkarm_nrf53_nrfjprogdll PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "nRF_FAMILY=NRF53_FAMILY"
)

# Create imported target nrftools::jlinkarm_nrf91_nrfjprogdll
add_library(nrftools::jlinkarm_nrf91_nrfjprogdll SHARED IMPORTED)

set_target_properties(nrftools::jlinkarm_nrf91_nrfjprogdll PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "nRF_FAMILY=NRF91_FAMILY"
)

# Create imported target nrftools::jlinkarm_unknown_nrfjprogdll
add_library(nrftools::jlinkarm_unknown_nrfjprogdll SHARED IMPORTED)

set_target_properties(nrftools::jlinkarm_unknown_nrfjprogdll PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "nRF_FAMILY=UNKNOWN_FAMILY"
)

# Create imported target nrftools::nrfjprogexe
add_executable(nrftools::nrfjprogexe IMPORTED)

set_target_properties(nrftools::nrfjprogexe PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "COMPILE_EXE"
)

# Create imported target nrftools::mergehex
add_executable(nrftools::mergehex IMPORTED)

set_target_properties(nrftools::mergehex PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "COMPILE_EXE"
)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/NRFCommandLineToolsTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
